version: '3.7'

services:
  db:
    restart: always
    volumes:
      - wordpress_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpresspass

  cms:
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpresspass

  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
    - 9000:9000
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer_data:/data

  watchtower:
    image: v2tec/watchtower
    command: --debug
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

volumes:
  wordpress_data:
  portainer_data:
