version: '3.4'

services:

  db:
    image: mysql:5.7
    volumes:
      - wp_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_INST}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}

  wordpress:
    depends_on:
      - db
    image: wordpress:4.9.8-php7.1-apache
    volumes:
      - ./plugins/storytelling:/var/www/html/wp-content/plugins/eagle-storytelling-application
    ports:
      - 81:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}

volumes:
  wp_data:

