version: '3.7'

services:
  db:
    restart: always
    volumes:
      - wordpress_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpresspass

  cms:
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpresspass

  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
    - 9000:9000
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer_data:/data

  watchtower:
    image: v2tec/watchtower
    command: --debug
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    #- /root/.docker/config.json:/config.json
    environment:
      REPO_USER: dainstmaintenance
      REPO_PASS: dainstmaintenancepass
      WATCHTOWER_NOTIFICATIONS_LEVEL: debug
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: dev@dainst.de
      WATCHTOWER_NOTIFICATION_EMAIL_TO: dev@dainst.de
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: mail.dainst.de
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: dev@dainst.de
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: devpass

volumes:
  wordpress_data:
  portainer_data:
