version: '3.1'

services:

  wordpress:
    image: wordpress:4.9.8-php7.1-apache
    ports:
    - 81:80
    environment:
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    volumes:
    - ./plugins/storytelling:/var/www/html/wp-content/plugins/eagle-storytelling-application

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}